"""empty message

Revision ID: d5c194451db7
Revises: c6c374ee6b6e
Create Date: 2019-07-04 20:05:41.900901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5c194451db7'
down_revision = 'c6c374ee6b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('noticias', sa.Column('imagem', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('noticias', 'imagem')
    # ### end Alembic commands ###
